apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.name }}-datasource
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ tpl .Values.prometheus.url . }}
        isDefault: true
        editable: true