apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}
spec:
  selector:
    app: {{ .Values.prometheus.name }}
  ports:
    - port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}